"""Generate the Phase 5 synthetic delivery scenarios and persist them to
config/synthetic_scenarios.yaml -- the synthetic analog of
generate_scenarios.py, kept in a separate file from the real
config/scenarios.yaml so the two pipelines never mix.

Campaigns here are just example ids (CAMPAIGN_IDS below); nothing about
synthetic_world.py or synthetic.py limits the population to these four --
see synthetic_world.py's module docstring on why campaigns are sampled on
the fly rather than a fixed roster.

Run once relative to a given synthetic_world.json + synthetic.py; re-run
(after deleting the output file) if generation logic or the world changes.
"""

import sys
import time
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from adtech_rtb.synthetic import generate_synthetic_scenarios  # noqa: E402
from adtech_rtb.synthetic_world import load_world  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
WORLD_PATH = REPO_ROOT / "data" / "interim" / "synthetic_world.json"
SCENARIOS_PATH = REPO_ROOT / "config" / "synthetic_scenarios.yaml"

CAMPAIGN_IDS = ["synthA", "synthB", "synthC", "synthD"]
N_PER_CAMPAIGN = 3


def main() -> None:
    world = load_world(WORLD_PATH)

    t0 = time.time()
    scenarios = generate_synthetic_scenarios(world, CAMPAIGN_IDS, n_per_campaign=N_PER_CAMPAIGN, seed=42)
    print(f"Generated {len(scenarios)} scenarios in {time.time() - t0:.1f}s", flush=True)

    for s in scenarios:
        print(
            f"  {s['id']}: flight_length_days={s['flight_length_days']}, "
            f"n_eligible={s['n_eligible_auctions']:,}, target={s['target_impressions']:,}, "
            f"ctr_floor={s['ctr_floor']:.5f} (pop. mean {s['population_mean_ctr']:.5f}), "
            f"reachable={s['naive_baseline_reachable']}",
            flush=True,
        )

    unreachable = [s["id"] for s in scenarios if not s["naive_baseline_reachable"]]
    if unreachable:
        print(f"\nWarning: {len(unreachable)} scenario(s) not reachable within bid bounds: {unreachable}")

    SCENARIOS_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(SCENARIOS_PATH, "w") as f:
        f.write(
            "# Generated by scripts/generate_synthetic_scenarios.py -- do not hand-edit.\n"
            "# Regenerate by deleting this file and re-running that script (fixed seed,\n"
            "# so output is deterministic for a given synthetic_world.json + synthetic.py).\n"
        )
        yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=False)
    print(f"\nWrote {len(scenarios)} scenarios -> {SCENARIOS_PATH}")


if __name__ == "__main__":
    main()
