"""Generate the random delivery scenarios shared by the naive baseline and
the bandit, and persist them into config/scenarios.yaml.

Checkpointed to data/interim/scenarios_checkpoint.jsonl, one line per
scenario, flushed immediately after each is built -- each scenario's
random draws are seeded from (seed, advertiser_id, its own index, attempt
number), not one shared mutating rng (see scenarios.iter_scenarios), so a
re-run after an interruption skips every id already in the checkpoint and
reproduces the rest bit-for-bit, rather than starting over. Delete the
checkpoint file to force a clean regenerate (e.g. after changing
N_PER_ADVERTISER or the generation logic in scenarios.py -- a stale
checkpoint from different logic would silently mix old- and new-logic
scenarios under the same ids).

Run once relative to a given scenarios.py; re-run only if generation
logic changes, since the naive baseline and the Phase 3 bandit both need
to be evaluated against the exact same committed scenario set.
"""

import json
import sys
from pathlib import Path

import lightgbm as lgb
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from adtech_rtb.market_model import RAW_COLUMNS  # noqa: E402
from adtech_rtb.scenarios import iter_scenarios  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = REPO_ROOT / "data" / "processed"
MODELS_DIR = REPO_ROOT / "models"
CONFIG_PATH = REPO_ROOT / "config" / "config.yaml"
CHECKPOINT_PATH = REPO_ROOT / "data" / "interim" / "scenarios_checkpoint.jsonl"

N_PER_ADVERTISER = 3


def _load_checkpoint() -> dict[str, dict]:
    if not CHECKPOINT_PATH.exists():
        return {}
    checkpointed = {}
    with open(CHECKPOINT_PATH) as f:
        for line in f:
            line = line.strip()
            if line:
                s = json.loads(line)
                checkpointed[s["id"]] = s
    return checkpointed


def main() -> None:
    with open(CONFIG_PATH) as f:
        config = yaml.safe_load(f)
    advertiser_ids = [a["id"] for a in config["advertisers"]]

    checkpointed = _load_checkpoint()
    if checkpointed:
        print(f"Resuming: {len(checkpointed)} scenario(s) already checkpointed at {CHECKPOINT_PATH}")

    market_booster = lgb.Booster(model_file=str(MODELS_DIR / "market_model.txt"))
    with open(MODELS_DIR / "market_category_maps.json") as f:
        market_category_maps = json.load(f)

    ctr_booster = lgb.Booster(model_file=str(MODELS_DIR / "ctr_model.txt"))
    with open(MODELS_DIR / "ctr_category_maps.json") as f:
        ctr_category_maps = json.load(f)

    print("Loading test set (raw columns, pre-feature-engineering)...", flush=True)
    test_df = pd.read_parquet(PROCESSED_DIR / "test.parquet", columns=RAW_COLUMNS, dtype_backend="pyarrow")
    print(f"Loaded {len(test_df):,} rows.", flush=True)

    CHECKPOINT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(CHECKPOINT_PATH, "a") as ckpt_f:
        for s in iter_scenarios(
            test_df,
            market_booster,
            market_category_maps,
            ctr_booster,
            ctr_category_maps,
            advertiser_ids,
            n_per_advertiser=N_PER_ADVERTISER,
            skip_ids=frozenset(checkpointed.keys()),
        ):
            ckpt_f.write(json.dumps(s) + "\n")
            ckpt_f.flush()
            geo = f"region={s['region_ids']}" + (f", city={s['city_ids']}" if s["city_ids"] else "")
            print(
                f"  {s['id']}: {geo}, flight_length_days={s['flight_length_days']}, "
                f"n_eligible={s['n_eligible_auctions']:,}, target={s['target_impressions']:,}, "
                f"ctr_floor={s['ctr_floor']:.5f} (pop. mean {s['population_mean_ctr']:.5f}), "
                f"reachable={s['naive_baseline_reachable']}",
                flush=True,
            )
            checkpointed[s["id"]] = s

    scenarios = list(checkpointed.values())
    unreachable = [s["id"] for s in scenarios if not s["naive_baseline_reachable"]]
    if unreachable:
        print(f"\nWarning: {len(unreachable)} scenario(s) not reachable within bid bounds: {unreachable}")

    scenarios_path = REPO_ROOT / config["scenarios_file"]
    with open(scenarios_path, "w") as f:
        f.write(
            "# Generated by scripts/generate_scenarios.py -- do not hand-edit.\n"
            "# Regenerate by deleting data/interim/scenarios_checkpoint.jsonl and\n"
            "# re-running that script (fixed seed, so output is deterministic for a\n"
            "# given src/adtech_rtb/scenarios.py).\n"
        )
        yaml.dump({"scenarios": scenarios}, f, default_flow_style=False, sort_keys=False)
    print(f"\nWrote {len(scenarios)} scenarios -> {scenarios_path}")


if __name__ == "__main__":
    main()
